# Generated by Django 4.2.27 on 2025-12-04 21:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_master",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the master account for data fetching?",
                    ),
                ),
                (
                    "is_breakout_cash_active",
                    models.BooleanField(
                        default=True, verbose_name="Bull Engine Master Switch"
                    ),
                ),
                ("breakout_start_time", models.TimeField(default=datetime.time(9, 15))),
                ("breakout_end_time", models.TimeField(default=datetime.time(15, 15))),
                (
                    "breakout_max_total_trades",
                    models.IntegerField(
                        default=10, help_text="Max Bull trades per day"
                    ),
                ),
                (
                    "breakout_per_trade_sl_amount",
                    models.FloatField(
                        default=1000.0, help_text="Max Rupees risk per Bull trade"
                    ),
                ),
                (
                    "breakout_volume_price_threshold",
                    models.FloatField(
                        default=5000000.0, help_text="Min Volume*Price (Rupees)"
                    ),
                ),
                (
                    "is_breakdown_cash_active",
                    models.BooleanField(
                        default=True, verbose_name="Bear Engine Master Switch"
                    ),
                ),
                (
                    "breakdown_start_time",
                    models.TimeField(default=datetime.time(9, 15)),
                ),
                ("breakdown_end_time", models.TimeField(default=datetime.time(15, 15))),
                (
                    "breakdown_max_total_trades",
                    models.IntegerField(
                        default=10, help_text="Max Bear trades per day"
                    ),
                ),
                (
                    "breakdown_per_trade_sl_amount",
                    models.FloatField(
                        default=1000.0, help_text="Max Rupees risk per Bear trade"
                    ),
                ),
                (
                    "breakdown_volume_price_threshold",
                    models.FloatField(
                        default=5000000.0, help_text="Min Volume*Price (Rupees)"
                    ),
                ),
                ("breakout_pnl_exit_enabled", models.BooleanField(default=False)),
                (
                    "breakout_pnl_profit_target_amount",
                    models.FloatField(default=5000.0),
                ),
                ("breakout_pnl_stop_loss_amount", models.FloatField(default=2000.0)),
                ("breakdown_pnl_exit_enabled", models.BooleanField(default=False)),
                (
                    "breakdown_pnl_profit_target_amount",
                    models.FloatField(default=5000.0),
                ),
                ("breakdown_pnl_stop_loss_amount", models.FloatField(default=2000.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashBreakoutTrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Trigger"),
                            ("PENDING_ENTRY", "Entry Submitted"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Exit Submitted"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("FAILED_ENTRY", "Entry Failed"),
                            ("FAILED_EXIT", "Exit Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("candle_ts", models.DateTimeField(blank=True, null=True)),
                ("candle_open", models.FloatField(default=0.0)),
                ("candle_high", models.FloatField(default=0.0)),
                ("candle_low", models.FloatField(default=0.0)),
                ("candle_close", models.FloatField(default=0.0)),
                ("candle_volume", models.IntegerField(default=0)),
                ("volume_price", models.FloatField(default=0.0)),
                ("entry_level", models.FloatField(help_text="Trigger Price")),
                ("stop_level", models.FloatField(help_text="Stop Loss Price")),
                ("target_level", models.FloatField(help_text="Target Price")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.FloatField(default=0.0)),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prev_day_high", models.FloatField(default=0.0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bull Trade",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashBreakdownTrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Trigger"),
                            ("PENDING_ENTRY", "Entry Submitted"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Exit Submitted"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("FAILED_ENTRY", "Entry Failed"),
                            ("FAILED_EXIT", "Exit Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("candle_ts", models.DateTimeField(blank=True, null=True)),
                ("candle_open", models.FloatField(default=0.0)),
                ("candle_high", models.FloatField(default=0.0)),
                ("candle_low", models.FloatField(default=0.0)),
                ("candle_close", models.FloatField(default=0.0)),
                ("candle_volume", models.IntegerField(default=0)),
                ("volume_price", models.FloatField(default=0.0)),
                ("entry_level", models.FloatField(help_text="Trigger Price")),
                ("stop_level", models.FloatField(help_text="Stop Loss Price")),
                ("target_level", models.FloatField(help_text="Target Price")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.FloatField(default=0.0)),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prev_day_low", models.FloatField(default=0.0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bear Trade",
                "ordering": ["-created_at"],
            },
        ),
    ]
