# Generated by Django 4.2.27 on 2025-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_account_api_secret_alter_account_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="breakdown_max_total_trades",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakdown_per_trade_sl_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakdown_pnl_exit_enabled",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakdown_pnl_profit_target_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakdown_pnl_stop_loss_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakdown_volume_price_threshold",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_max_total_trades",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_per_trade_sl_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_pnl_exit_enabled",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_pnl_profit_target_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_pnl_stop_loss_amount",
        ),
        migrations.RemoveField(
            model_name="account",
            name="breakout_volume_price_threshold",
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_max_trades",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_risk_reward",
            field=models.CharField(default="1:2", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_risk_trade_1",
            field=models.FloatField(default=2000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_risk_trade_2",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_risk_trade_3",
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_trades_per_stock",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="account",
            name="breakdown_trailing_sl",
            field=models.CharField(default="1:1", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_max_trades",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_risk_reward",
            field=models.CharField(default="1:2", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_risk_trade_1",
            field=models.FloatField(default=2000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_risk_trade_2",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_risk_trade_3",
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_trades_per_stock",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="account",
            name="breakout_trailing_sl",
            field=models.CharField(default="1:1", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="max_daily_loss",
            field=models.FloatField(default=2000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="max_daily_profit",
            field=models.FloatField(default=5000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="pnl_exit_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="volume_settings_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_breakdown_cash_active",
            field=models.BooleanField(default=True, verbose_name="Bear Engine Switch"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_breakout_cash_active",
            field=models.BooleanField(default=True, verbose_name="Bull Engine Switch"),
        ),
    ]
