# Generated by Django 4.2.27 on 2025-12-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_remove_account_breakdown_max_total_trades_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="volume_settings_json",
        ),
        migrations.AddField(
            model_name="account",
            name="bear_volume_settings_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of 10 Bear Volume Criteria Levels",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bull_volume_settings_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of 10 Bull Volume Criteria Levels",
                null=True,
            ),
        ),
    ]
