# Generated by Django 4.2.27 on 2025-12-17 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading", "0004_remove_account_volume_settings_json_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbreakdowntrade",
            options={"verbose_name": "Bear Trade"},
        ),
        migrations.AlterModelOptions(
            name="cashbreakouttrade",
            options={"verbose_name": "Bull Trade"},
        ),
        migrations.AddField(
            model_name="account",
            name="is_mom_bear_active",
            field=models.BooleanField(
                default=True, verbose_name="Momentum Bear Switch"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_mom_bull_active",
            field=models.BooleanField(
                default=True, verbose_name="Momentum Bull Switch"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_max_trades",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_risk_per_trade",
            field=models.FloatField(default=2000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_risk_reward",
            field=models.CharField(default="1:2", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_stop_loss_pct",
            field=models.FloatField(default=0.5, help_text="Fixed SL % (e.g. 0.5)"),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_trailing_sl",
            field=models.CharField(default="1:1.5", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bear_volume_settings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_max_trades",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_risk_per_trade",
            field=models.FloatField(default=2000.0),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_risk_reward",
            field=models.CharField(default="1:2", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_stop_loss_pct",
            field=models.FloatField(default=0.5, help_text="Fixed SL % (e.g. 0.5)"),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_trailing_sl",
            field=models.CharField(default="1:1.5", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="mom_bull_volume_settings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bear_volume_settings_json",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bull_volume_settings_json",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name="MomentumBullTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Trigger"),
                            ("PENDING_ENTRY", "Entry Submitted"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Exit Submitted"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("FAILED_ENTRY", "Entry Failed"),
                            ("FAILED_EXIT", "Exit Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("candle_ts", models.DateTimeField(blank=True, null=True)),
                ("candle_open", models.FloatField(default=0.0)),
                ("candle_high", models.FloatField(default=0.0)),
                ("candle_low", models.FloatField(default=0.0)),
                ("candle_close", models.FloatField(default=0.0)),
                ("candle_volume", models.IntegerField(default=0)),
                ("volume_price", models.FloatField(default=0.0)),
                ("entry_level", models.FloatField(help_text="Trigger Price")),
                ("stop_level", models.FloatField(help_text="Stop Loss Price")),
                ("target_level", models.FloatField(help_text="Target Price")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.FloatField(default=0.0)),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_candle_high", models.FloatField(default=0.0)),
                ("prev_day_close", models.FloatField(default=0.0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Momentum Bull Trade",
            },
        ),
        migrations.CreateModel(
            name="MomentumBearTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Trigger"),
                            ("PENDING_ENTRY", "Entry Submitted"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Exit Submitted"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("FAILED_ENTRY", "Entry Failed"),
                            ("FAILED_EXIT", "Exit Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("candle_ts", models.DateTimeField(blank=True, null=True)),
                ("candle_open", models.FloatField(default=0.0)),
                ("candle_high", models.FloatField(default=0.0)),
                ("candle_low", models.FloatField(default=0.0)),
                ("candle_close", models.FloatField(default=0.0)),
                ("candle_volume", models.IntegerField(default=0)),
                ("volume_price", models.FloatField(default=0.0)),
                ("entry_level", models.FloatField(help_text="Trigger Price")),
                ("stop_level", models.FloatField(help_text="Stop Loss Price")),
                ("target_level", models.FloatField(help_text="Target Price")),
                ("quantity", models.IntegerField(default=0)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.FloatField(default=0.0)),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_candle_low", models.FloatField(default=0.0)),
                ("prev_day_close", models.FloatField(default=0.0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Momentum Bear Trade",
            },
        ),
    ]
