# Generated by Django 4.2.27 on 2025-12-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_bannedsymbol_alter_cashbreakdowntrade_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_master",
            field=models.BooleanField(
                default=False, help_text="Designate as master for fetching instruments"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
